version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: registry:REGISTRY_PORT
  tls:
    certificate: CERTS_/certs/REGISTRY_DOMAIN_NAME.crt
    key: CERTS_/private/REGISTRY_DOMAIN_NAME.key
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3