ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
CREATE USER 'MYSQL_ADMIN_USER'@'%' IDENTIFIED BY 'MYSQL_ADMIN_USER_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_ADMIN_USER'@'%';
FLUSH PRIVILEGES;
QUIT